[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # Exclude a few files that are problematic
  services/strategy-service/src/backtrader/.*
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = [
    "services/strategy-service/src/backtrader/*",
    "services/strategy-service/src/backtrader/**/*"
]
