global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bifrost-services'
    static_configs:
      - targets: 
        - 'api-gateway:8000'
        - 'data-service:8001'
        - 'portfolio-service:8002'
        - 'strategy-service:8003'
        - 'execution-service:8004'
        - 'risk-service:8005'
        - 'web-portal:8006'
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
