name: AI Collaboration Quality Check

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  ai-quality-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy
      
      - name: Run AI Quality Check
        run: |
          python scripts/ai-quality-check.py $(find . -name "*.py" -not -path "./venv/*" -not -path "./.git/*")
      
      - name: Check Code Formatting
        run: |
          black --check .
          isort --check-only .
      
      - name: Run Linting
        run: |
          flake8 .
      
      - name: Run Type Checking
        run: |
          mypy . --ignore-missing-imports

  documentation-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
      
      - name: Build Documentation
        run: |
          mkdocs build
      
      - name: Validate Documentation Structure
        run: |
          # Check if main documentation files exist
          test -f docs/index.md
          test -f docs/architecture/overview.md
          test -f docs/services/data-service.md
          test -f mkdocs.yml
